[[redirects]]
  from = "/shared/*"
  to = "/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[plugins]]
package = "netlify-plugin-jest"

  [plugins.input]